---
- hosts: localhost
  become: no
  connection: local
  gather_facts: no
  tasks:
  - name: Create master internal elb
    ec2_elb_lb:
      name: openshift-master-{{ cluster_id }}-internal
      cross_az_load_balancing: yes
      region: "{{ ec2_region }}"
      scheme: internal
      state: present
      subnets: "{{ vpc_subnet_ids }}"
      security_group_ids: "{{ [master_internal_lb_sg.group_id] }}"
      health_check:
        ping_protocol: tcp
        ping_port: "{{ console_port }}"
        response_timeout: 2
        interval: 5
        unhealthy_threshold: 2
        healthy_threshold: 2
      listeners:
      - protocol: tcp
        load_balancer_port: "{{ console_port }}"
        instance_port: "{{ console_port }}"
    register: master_internal_elb

  - name: Create master external elb
    ec2_elb_lb:
      name: openshift-master-{{ cluster_id }}-external
      cross_az_load_balancing: yes
      region: "{{ ec2_region }}"
      state: present
      subnets: "{{ vpc_subnet_ids }}"
      security_group_ids: "{{ [master_external_lb_sg.group_id] }}"
      health_check:
        ping_protocol: tcp
        ping_port: "{{ console_port }}"
        response_timeout: 2
        interval: 5
        unhealthy_threshold: 2
        healthy_threshold: 2
      listeners:
      - protocol: tcp
        load_balancer_port: "{{ console_port }}"
        instance_port: "{{ console_port }}"
    register: master_external_elb

  - name: Create infra elb
    ec2_elb_lb:
      name: openshift-node-{{ cluster_id }}-infra
      cross_az_load_balancing: yes
      region: "{{ ec2_region }}"
      state: present
      subnets: "{{ vpc_subnet_ids }}"
      security_group_ids: "{{ [infra_lb_sg.group_id] }}"
      listeners:
      - protocol: tcp
        load_balancer_port: 443
        instance_port: 443
      - protocol: tcp
        load_balancer_port: 80
        instance_port: 80
      health_check:
        ping_protocol: tcp
        ping_port: 443
        response_timeout: 2
        interval: 5
        unhealthy_threshold: 2
        healthy_threshold: 2
    register: infra_elb

  - name: Create route53 entry for master internal elb
    route53:
      command: create
      zone: "{{ r53_zone }}"
      record: "openshift-internal.{{ r53_host_zone }}"
      ttl: 60
      type: A
      value: "{{ master_internal_elb.elb.dns_name }}"
      alias: yes
      alias_hosted_zone_id: "{{ master_internal_elb.elb.hosted_zone_id }}"
      overwrite: yes

  - name: Create route53 entry for master external elb
    route53:
      command: create
      zone: "{{ r53_zone }}"
      record: "{{ item }}"
      ttl: 60
      type: A
      value: "{{ master_external_elb.elb.hosted_zone_name }}"
      alias: yes
      alias_hosted_zone_id: "{{ master_external_elb.elb.hosted_zone_id }}"
      overwrite: yes
    with_items:
    - openshift-master.{{ r53_host_zone }}
    - openshift.{{ r53_host_zone }}

  - name: Create route53 entry for infra elb
    route53:
      command: create
      zone: "{{ r53_zone }}"
      record: "*.{{ r53_wildcard_zone }}"
      ttl: 60
      type: A
      value: "{{ infra_elb.elb.hosted_zone_name }}"
      alias: yes
      alias_hosted_zone_id: "{{ infra_elb.elb.hosted_zone_id }}"
      overwrite: yes
