# vim: set ft=ansible:
---
- name: Configure the VPC
  hosts: localhost
  gather_facts: no
  connection: local
  sudo: no
  vars:
    vpc_subnets: "{{ lookup('ec2_zones_by_region', ec2_region) | oo_split
                     | oo_subnets_from_zones('172.18.', cluster_id) }}"
  tasks:
  - fail:
      msg: required values not set
    when: ec2_region is not defined or cluster_id is not defined

  - name: Create ec2 vpc
    ec2_vpc:
      state: present
      dns_support: yes
      dns_hostnames: yes
      cidr_block: 172.18.0.0/16
      resource_tags:
        env: "{{ cluster_id }}"
        Name: "{{ cluster_id }}-vpc"
      region: "{{ ec2_region }}"
      subnets: "{{ vpc_subnets }}"
      internet_gateway: yes
      route_tables:
      - subnets: "{{ vpc_subnets | oo_collect('cidr') }}"
        routes:
        - dest: 0.0.0.0/0
          gw: igw
        resource_tags:
          Name: "{{ cluster_id }}-route"
          env: "{{ cluster_id }}"
      wait: yes
    register: vpc
