# vim: set ft=ansible:
- name: Repository configuration
  hosts: cluster_hosts
  tasks:
  - name: Configure OSE repository
    copy:
      src: ../files/ose3.repo
      dest: /etc/yum.repos.d/ose3.repo
      mode: 0644
      owner: root
      group: root
    when: skip_subscription_management | bool

  - name: Enable rhui extras channel
    command: yum-config-manager --enable rhui-REGION-rhel-server-extras
    when: skip_subscription_management | bool

  - name: Update current package set
    yum:
      name: '*'
      state: latest
    when: skip_subscription_management | bool
