---
- hosts: localhost
  connection: local
  become: no
  gather_facts: no
  vars_files:
  - vars.yml
  tasks:
  - name: Find the cluster hosts
    add_host:
      name: "{{ item }}"
      ansible_ssh_user: openshift
      ansible_sudo: yes
      groups: oo_hosts_to_unregister
    with_items: groups['tag_openshift-demo-_' ~ cluster_id] | default([], True)

- name: Unregister host(s)
  hosts: oo_hosts_to_unregister
  serial: 1
  tasks:
  - name: Unregister host
    redhat_subscription:
      username: "{{ rhsm_user }}"
      password: "{{ rhsm_pass }}"
      state: absent
    when: not (skip_subscription_management | bool)

- name: Delete the EC2 items 
  hosts: localhost
  connection: local
  become: no
  gather_facts: no
  vars_files:
  - vars.yml
  tasks:
  - name: Delete the Route53 entry for master
    route53:
      command: delete
      zone: "{{ r53_zone }}"
      record: "openshift-master.{{ r53_host_zone }}"
      ttl: 60
      type: A
      value: "{{ hostvars[groups['tag_openshift-demo-' ~ cluster_id ~ '-host-type_master'].0]['ec2_ip_address'] }}"
      overwrite: yes

  - name: Destroy the CloudFormation Stack
    cloudformation:
      region: "{{ ec2_region }}"
      stack_name: openshift-demo-{{ cluster_id }}
      state: absent
      template: files/cloudformation.json
