# vim: set ft=ansible:
---
- hosts: localhost
  connection: local
  sudo: no
  gather_facts: no
  vars:
    project_master: "{{ groups['tag_openshift-demo-' ~ cluster_id ~ '-host-type_master'].0 }}"
  tasks:
  - name: Create group for first master
    add_host:
      name: "{{ project_master }}"
      groups: project_master

- hosts: project_master
  gather_facts: yes
  sudo: no
  tasks:
  - debug: var=hostvars
  - route53:
      command: create
      zone: "{{ r53_zone }}"
      record: "openshift-master.{{ r53_host_zone }}"
      ttl: 60
      type: A
      value: "{{ hostvars[groups['tag_openshift-demo-' ~ cluster_id ~ '-host-type_master'].0]['ec2_ip_address'] }}"
      overwrite: yes
    delegate_to: localhost
